### ISSUE TITLE
Request for Morphius Touchpad 20240120.rom if feasible

### ISSUE THREAD

**Issue by Firminator** [MrChromebox/scripts#353]
https://github.com/MrChromebox/scripts/blob/2c2150ff7ff83a4d5665f42613a1a3aaa7bb1bbc/sources.sh#L303
The script still points to the January 7th release. Any way in the near future to get the touchpad-enabled release of 4.22.2 or are the fixes just Windows-related as the changelog on your site indicates?

**Comment by MrChromebox** [comment]
done

**Comment by Firminator** [comment]
That was fast. Thanks. Flashed fine here.
[Still got a lot of dmesg errors and audio still doesn't work but that might still be kernel related.]
